import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:jarvis/core/config/strings.dart';
import 'package:jarvis/core/config/theme.dart';
import 'package:jarvis/core/router/app_router.dart';
import 'package:jarvis/core/sync/sync_provider.dart';

/// Root widget of the Jarvis app.
///
/// [ConsumerWidget] gives access to Riverpod providers.
/// The router is provided by [appRouterProvider] which is defined in
/// core/router/app_router.dart and generated by riverpod_generator.
class JarvisApp extends ConsumerWidget {
  const JarvisApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);
    // Initialize the sync notifier so it registers its lifecycle observer and
    // auth listener. keepAlive: true ensures it stays alive for the full session.
    ref.read(syncNotifierProvider);

    return MaterialApp.router(
      title: AppStrings.appName,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.system, // Respects device dark/light setting
      routerConfig: router,
      debugShowCheckedModeBanner: false,
    );
  }
}
