import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:jarvis/core/config/strings.dart';
import 'package:jarvis/core/router/app_router.dart';
import 'package:jarvis/core/sync/sync_provider.dart';
import 'package:jarvis/core/theme/app_theme.dart';

/// Root widget of the Jarvis app.
///
/// [ConsumerWidget] gives access to Riverpod providers.
/// The router is provided by [appRouterProvider] which is defined in
/// core/router/app_router.dart and generated by riverpod_generator.
///
/// Theme: dark-first. Light mode is Phase 5 work.
class JarvisApp extends ConsumerWidget {
  const JarvisApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);
    // Initialize the sync notifier so it registers its lifecycle observer and
    // auth listener. keepAlive: true ensures it stays alive for the full session.
    ref.read(syncNotifierProvider);

    return MaterialApp.router(
      title: AppStrings.appName,
      // Dark-only for Phase 1.5 — ThemeMode.dark ignores the device setting
      // and always uses our custom dark theme. Light mode in Phase 5.
      theme: AppTheme.dark,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.dark,
      routerConfig: router,
      debugShowCheckedModeBanner: false,
    );
  }
}
